# name: CI/CD - Microservices

# on:

#   push:
#     branches: [main]
#     paths:
#       - 'services/**'
#       - '.github/workflows/ci-cd.yml'

# env:
#   AWS_REGION: us-east-1
#   ECR_PATIENT_REPO: your_ecr_repo_name/patient-service
#   ECR_APPOINTMENT_REPO: your_ecr_repo_name/appointment-service

# jobs:
#   deploy-services:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:

#           role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_GITHUB_OIDC_ROLE
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build & Push Patient Service Image
#         run: |
#           docker build -t $ECR_PATIENT_REPO:latest ./services/patient-service
#           docker push $ECR_PATIENT_REPO:latest

#       - name: Build & Push Appointment Service Image
#         run: |
#           docker build -t $ECR_APPOINTMENT_REPO:latest ./services/appointment-service
#           docker push $ECR_APPOINTMENT_REPO:latest

#       - name: Update ECS Services (Optional)
#         run: |
#           aws ecs update-service \
#             --cluster healthcare-app-cluster \
#             --service patient-service \
#             --force-new-deployment
          

#           aws ecs update-service \
#             --cluster healthcare-app-cluster \
#             --service appointment-service \
#             --force-new-deployment